apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsrv

spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsrv
  template:
    metadata:
      labels:
        app: appsrv
    spec:
      containers:
        - name: appsrv
          image: ghcr.io/htl-leo-itp-2325-4-5ahitm/jungle-book-backend:latest
          # remove this when stable. Currently we do not take care of version numbers
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: jungle-book-data
              mountPath: /media/jungle-book
      volumes:
        - name: jungle-book-data
          persistentVolumeClaim:
            claimName: jungle-book-data

---
apiVersion: v1
kind: Service
metadata:
  name: appsrv

spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: appsrv
