# Quarkus Application Server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.0.0
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME_URL
              value: "https://it200247.cloud.htl-leonding.ac.at/auth" 
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KC_HTTP_ENABLED
              value: 'false'
            - name: KC_HOSTNAME_STRICT
              value: 'true'
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: 'false'
          command: ["/opt/keycloak/bin/kc.sh", "start-dev", "--proxy", "edge", "--hostname-admin-url=http://it200247.cloud.htl-leonding.ac.at/auth"]           
          ports:
            - containerPort: 8080
              name: keycloak
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
